import toJD from "../src/julian";

// Generated by CodiumAI

describe("toJD", () => {
  // Calculates the Julian Day for a given date.
  it("should calculate the Julian Day for a given date", () => {
    // Arrange
    const year = 2022;
    const month = 10;
    const day = 15;

    // Act
    const result = toJD(year, month, day);

    // Assert
    expect(result).toBe(2459867.5);
  });

  // Handles February 29th correctly for leap years.
  // Handles leap years correctly.
  it("should handle February 29th correctly for leap years", () => {
    // Arrange
    const year = 2020;
    const month = 2;
    const day = 29;

    // Act
    const result = toJD(year, month, day);

    // Assert
    expect(result).toBe(2458908.5);
  });

  // Returns the calculated Julian Day (JD) for the given date.
  // Handles valid input values for year, month, and day.
  // Handles dates from the Gregorian calendar reform (after October 4, 1582) correctly.
  it("should calculate the Julian Day for a given date and should calculate the Julian Day for a date after the Gregorian calendar reform", () => {
    // Arrange
    const year = 2022;
    const month = 10;
    const day = 15;

    // Act
    const result = toJD(year, month, day);

    // Assert
    expect(result).toBe(2459867.5);
  });

  // Handles dates before the Gregorian calendar reform (before October 4, 1582) correctly.
  it("should calculate the Julian Day for a date before the Gregorian calendar reform", () => {
    // Arrange
    const year = 1500;
    const month = 9;
    const day = 20;

    // Act
    const result = toJD(year, month, day);

    // Assert
    expect(result).toBe(2269185.5);
  });

  // Handles dates from the Julian calendar correctly.
  it("should calculate the Julian Day for a given date", () => {
    // Arrange
    const year = 2022;
    const month = 10;
    const day = 15;

    // Act
    const result = toJD(year, month, day);

    // Assert
    expect(result).toBe(2459867.5);
  });

  // Handles dates from the proleptic Gregorian calendar correctly.
  it("should calculate the Julian Day for a given date", () => {
    // Arrange
    const year = 2022;
    const month = 10;
    const day = 15;

    // Act
    const result = toJD(year, month, day);

    // Assert
    expect(result).toBe(2459867.5);
  });

  // Handles invalid input values for year, month, and day.
  it("should handle invalid input values for year, month, and day", () => {
    // Arrange
    const year = 2022;
    const month = 13;
    const day = 32;

    // Act
    const result = toJD(year, month, day);

    // Assert
    expect(result).toBeNaN();
  });

  // Handles negative input values for year, month, and day.
  it("should handle negative input values for year, month, and day", () => {
    // Arrange
    const year = -2022;
    const month = -10;
    const day = -15;

    // Act
    const result = toJD(year, month, day);

    // Assert
    expect(result).toBe(945664.5);
  });

  // Handles fractional input values for year, month, and day.
  it("should calculate the Julian Day for a given date with fractional input values", () => {
    // Arrange
    const year = 2022.5;
    const month = 10.5;
    const day = 15.5;

    // Act
    const result = toJD(year, month, day);

    // Assert
    expect(result).toBeNaN();
  });

  // Handles dates before the Julian calendar reform (before October 15, 1582) correctly.
  it("should calculate the Julian Day for a date before the Julian calendar reform", () => {
    // Arrange
    const year = 1582;
    const month = 10;
    const day = 4;

    // Act
    const result = toJD(year, month, day);

    // Assert
    expect(result).toBe(2299149.5);
  });

  // Handles dates from the Julian calendar reform (October 15-October 4, 1582) correctly.
  it("should calculate the Julian Day for a date within the Julian calendar reform", () => {
    // Arrange
    const year = 1582;
    const month = 10;
    const day = 15;

    // Act
    const result = toJD(year, month, day);

    // Assert
    expect(result).toBe(2299160.5);
  });

  // Handles dates from the proleptic Julian calendar correctly.
  it("should calculate the Julian Day for a given date", () => {
    // Arrange
    const year = 2022;
    const month = 10;
    const day = 15;

    // Act
    const result = toJD(year, month, day);

    // Assert
    expect(result).toBe(2459867.5);
  });

  // Handles dates from the proleptic Gregorian calendar before its introduction (before October 15, 1582) correctly.
  it("should calculate the Julian Day for a date before October 15, 1582", () => {
    // Arrange
    const year = 1500;
    const month = 9;
    const day = 30;

    // Act
    const result = toJD(year, month, day);

    // Assert
    expect(result).toBe(2269195.5);
  });

  // Handles dates from the proleptic Gregorian calendar after its introduction (after October 4, 1582) correctly.
  it("should calculate the Julian Day for a given date after October 4, 1582", () => {
    // Arrange
    const year = 2022;
    const month = 10;
    const day = 15;

    // Act
    const result = toJD(year, month, day);

    // Assert
    expect(result).toBe(2459867.5);
  });

  // Handles dates from the Swedish calendar reform (February 17, 1753) correctly.
  it("should calculate the Julian Day for a date after the Swedish calendar reform", () => {
    // Arrange
    const year = 1753;
    const month = 2;
    const day = 17;

    // Act
    const result = toJD(year, month, day);

    // Assert
    expect(result).toBe(2361377.5);
  });

  // Handles dates from the British calendar reform (September 14, 1752) correctly.
  it("should calculate the Julian Day for a date after the British calendar reform", () => {
    // Arrange
    const year = 1752;
    const month = 9;
    const day = 14;

    // Act
    const result = toJD(year, month, day);

    // Assert
    expect(result).toBe(2361221.5);
  });
});
